Document: font-grundschrift
Title: Debian font-grundschrift Manual
Author: <insert document author here>
Abstract: This manual describes what font-grundschrift is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/font-grundschrift/font-grundschrift.sgml.gz

Format: postscript
Files: /usr/share/doc/font-grundschrift/font-grundschrift.ps.gz

Format: text
Files: /usr/share/doc/font-grundschrift/font-grundschrift.text.gz

Format: HTML
Index: /usr/share/doc/font-grundschrift/html/index.html
Files: /usr/share/doc/font-grundschrift/html/*.html
